In [1]:
#Implementing a single perceptron model
import numpy as np
from sklearn.datasets import load_iris
from sklearn.linear_model import Perceptron

In [2]:
iris=load_iris()
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [3]:
X = iris.data[:,(2,3)]
y = (iris.target == 0).astype(np.int) # Modified the target to convert from multi class to binary classification

AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [ ]:
prcp = Perceptron() # Single perceptron model fitted
prcp.fit(X,y)

Perceptron()

In [4]:
prcp.predict([[1.2,3.4]]) # 2 square brackets for defining an array

NameError: name 'prcp' is not defined

In [6]:
#!pip uninstall tensorflow

In [7]:
#!pip install tensorflow==2.8.0

In [5]:
# To check if GPU is available for tensorflow or not
import tensorflow as tf
print("TensorFlow version:", tf.__version__)
print("GPU available:", tf.config.list_physical_devices('GPU'))

TensorFlow version: 2.10.0
GPU available: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [6]:
# MNIST Dataset
from tensorflow import keras

In [7]:
fashion_mnist_data = keras.datasets.fashion_mnist
(X_train,y_train),(X_test,y_test) = fashion_mnist_data.load_data()

4422102/4422102 [==============================] - 0s 0us/step


In [8]:
X_train.shape

(60000, 28, 28)

In [9]:
X_test.shape

(10000, 28, 28)

In [10]:
#Creating the validation dataset and removing those records from the train dataset
X_valid = X_train[:5000]
y_valid = y_train[:5000]
X_train = X_train[5000:]
y_train = y_train[5000:]

In [11]:
#Scaling the pixel intensities for training and validation datasets
X_valid = X_valid / 255.0
X_train = X_train / 255.0

In [12]:
y_train[0]

4

In [13]:
#Class labels values with names(obtained from keras documentation)
#0	T-shirt/top
#1	Trouser
#2	Pullover
#3	Dress
#4	Coat
#5	Sandal
#6	Shirt
#7	Sneaker
#8	Bag
#9	Ankle boot

In [14]:
class_names = ['T-shirt/top','Trouser','Pullover','Dress','Coat','Sandal','Shirt','Sneaker','Bag','Ankle Boot']

In [15]:
class_names[y_train[0]] # Mapping the class label name with the ouput

'Coat'

In [16]:
from keras.models import Sequential # Done so that we don't need to write keras.models.Sequential, and we can directly write Sequential
from keras.layers import Flatten
from keras.layers import Dense

In [17]:
model1 = Sequential( # If we wouldn't have imported Sequential earlier, we would have to write model = keras.models.Sequential
    [
        Flatten(input_shape=[28,28]),
        Dense(300,activation="relu"), # Hidden layer 1
        Dense(100,activation="relu"), # Hidden layer 2
        Dense(10,activation="softmax") # Output layer
    ]

)

In [18]:
# We can also build a model like this(we are instantiating a sequential model, then adding layers)
model2 = Sequential()
model2.add(Flatten(input_shape=[28,28]))
model2.add(Dense(300,activation="relu"))
model2.add(Dense(100,activation="relu"))
model2.add(Dense(10,activation="softmax"))

In [19]:
#Instead of directly writing the input shape inside flatten layer, we can also independently mention a input layer
from keras.layers import InputLayer
model3 = Sequential( # If we wouldn't have imported Sequential earlier, we would have to write model = keras.models.Sequential
    [
        Flatten(),
        InputLayer(input_shape=[28,28]),
        Dense(300,activation="relu"), # Hidden layer 1
        Dense(100,activation="relu"), # Hidden layer 2
        Dense(10,activation="softmax") # Output layer
    ]

)

In [20]:
model1.summary() # Get the summary of the model
#Layer 2 parameters = 784(no. of outputs of flatten layer) * 300 (no. of neurons of dense layer 1 i.e hidden layer 1) + 300 (no. of bias neurons in hidden layer 1)
#Layer 3 parameters = 300(no. of outputs of hidden layer 1) * 100 (no. of neurons of dense layer 2 i.e hidden layer 2) + 100 (no. of bias neurons in hidden layer 2)

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 300)               235500    
                                                                 
 dense_1 (Dense)             (None, 100)               30100     
                                                                 
 dense_2 (Dense)             (None, 10)                1010      
                                                                 
Total params: 266,610
Trainable params: 266,610
Non-trainable params: 0
_________________________________________________________________


In [21]:
model1.layers # Get info on the layers of the model

In [22]:
model1.layers[2].name # Get name of the layer

'dense_1'

In [23]:
weights , biases = model1.layers[2].get_weights() # To get the weights and biases of a layer in the model
weights

array([[-0.00248313,  0.06351917, -0.08374746, ...,  0.05977101,
        -0.10379165,  0.08376437],
       [ 0.02776597, -0.0748563 ,  0.05538628, ..., -0.0423418 ,
         0.07540553, -0.10614095],
       [-0.05487925, -0.07925309, -0.00584214, ...,  0.00222223,
        -0.00234191,  0.05152003],
       ...,
       [-0.0918914 , -0.0308326 , -0.00104928, ...,  0.00211421,
         0.03077423, -0.00748944],
       [ 0.02717724, -0.06663916, -0.11493433, ...,  0.09035585,
         0.03187341,  0.11450715],
       [-0.10077696,  0.05016763, -0.03768971, ..., -0.02229537,
         0.09682364,  0.0640623 ]], dtype=float32)

In [24]:
model1.compile(loss="sparse_categorical_crossentropy",optimizer="sgd",metrics=["accuracy"]) # Compilation of the model to specify loss , optmizer and metrics

In [25]:
model1.fit(X_train,y_train,epochs=30,validation_data=(X_valid,y_valid)) # Setting the input , then target column, then no. of epochs , then the validation data

Epoch 1/30
1719/1719 [==============================] - 8s 4ms/step - loss: 0.7165 - accuracy: 0.7632 - val_loss: 0.4979 - val_accuracy: 0.8324
Epoch 2/30
1719/1719 [==============================] - 6s 3ms/step - loss: 0.4882 - accuracy: 0.8290 - val_loss: 0.4650 - val_accuracy: 0.8332
Epoch 3/30
1719/1719 [==============================] - 6s 3ms/step - loss: 0.4413 - accuracy: 0.8443 - val_loss: 0.4745 - val_accuracy: 0.8270
Epoch 4/30
1719/1719 [==============================] - 6s 3ms/step - loss: 0.4135 - accuracy: 0.8547 - val_loss: 0.3996 - val_accuracy: 0.8618
Epoch 5/30
1719/1719 [==============================] - 5s 3ms/step - loss: 0.3931 - accuracy: 0.8631 - val_loss: 0.4084 - val_accuracy: 0.8568
Epoch 6/30
1719/1719 [==============================] - 6s 3ms/step - loss: 0.3771 - accuracy: 0.8665 - val_loss: 0.3876 - val_accuracy: 0.8620
Epoch 7/30
1719/1719 [==============================] - 5s 3ms/step - loss: 0.3642 - accuracy: 0.8717 - val_loss: 0.3555 - val_accuracy:

In [31]:
# When the dataset is imbalanced, use this to give more weight to lower populated class
#model1.fit(X_train,y_train,epochs=30,validation_data=(X_valid,y_valid),class_weight={0:2, 1:1})
#Class 0 is assigned a weight of 2 and class 1 is assigned a weight of 1.

In [33]:
model1.evaluate(X_test,y_test) # For evaluating the model on the test dataset

313/313 [==============================] - 1s 4ms/step - loss: 63.2068 - accuracy: 0.8496


[63.20681381225586, 0.8496000170707703]

In [37]:
#Prediction on new data
X_new = X_test[:5]
y_pred = model1.predict(X_new)
y_pred

1/1 [==============================] - 0s 20ms/step


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]], dtype=float32)

In [40]:
# Converting the predictions into list of labels, to be used to predict the class
labels_list = tf.argmax(y_pred, axis=1)
labels_list

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([9, 2, 1, 1, 6])>

In [44]:
pred_class = np.array(class_names)[labels_list]
pred_class

array(['Ankle Boot', 'Pullover', 'Trouser', 'Trouser', 'Shirt'],
      dtype='<U11')